### ISSUE TITLE
Bad lower bound on hspec

### ISSUE THREAD

**Issue by MasseR** [parsonsmatt/hspec-hedgehog#13]
The hspec bounds are marked as

```
    , hspec         >= 2.4.4 && < 3
```

but you are trying to import [modifyArgs](https://github.com/parsonsmatt/hspec-hedgehog/blob/master/src/Test/Hspec/Hedgehog.hs#L112) which is introduced in [hspec-2.5.8](https://hackage.haskell.org/package/hspec-2.5.8/docs/Test-Hspec-QuickCheck.html).

**Comment by parsonsmatt** [comment]
Great catch, thanks!
