### ISSUE TITLE
I think `modifyMaxSize` has no effect

### ISSUE THREAD

**Issue by ChickenProp** [parsonsmatt/hspec-hedgehog#22]
This function is re-exported from Test.Hspec.QuickCheck, but it looks to me like it has (and can have) no effect. `maxSize` of the quickcheck args isn't used, and I believe Hedgehog currently has no way to set the max size for a test. I guess it would be worth documenting this, and not re-exporting the function.

**Comment by sol** [comment]
PR welcome!
