### ISSUE TITLE
How would I use hedgehog-classes with this?

### ISSUE THREAD

**Issue by kozross** [parsonsmatt/hspec-hedgehog#8]
It's not immediately apparent to me how I could use this to test various type class laws in Hspec. Would some support be possible?

**Comment by parsonsmatt** [comment]
The functions in `hedgehog-classes` return `IO Bool`, where `True` indicates that the laws pass. `hspec` tests let you run `IO` actions in the example blocks.

```haskell
spec :: Spec
spec = do
  describe "Monoid Ordering" $ do
    it "satisfies the laws" $ do
      result <- lawsCheck (monoidLaws genOrdering)
      result `shouldBe` True
```

You can simplify this to:

```haskell
it "satisfies the laws" $ do
  lawsCheck (monoidLaws genOrdering)
    `shouldReturn` True
```

Or define a helper function:

```haskell
hedgeLaws :: String -> IO Bool -> IO ()
hedgeLaws message action = 
  it message $ 
    action `shouldReturn` Bool

spec :: Spec
spec = do
  describe "Monoid ordering" $ do
    hedgeLaws "works" $ monoidLaws genOrdering
```

**Comment by kozross** [comment]
This approach only runs one example. Is there a way I could run more?
